apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: workloads
  sources:
    - repoURL: ghcr.io/murillo-consulting
      chart: kube-aegis-forge
      targetRevision: 0.4.0
      helm:
        releaseName: demo-api
        valueFiles:
          - $images/platform/environments/local/image-values.yaml
        valuesObject:
          nameOverride: demo-api
          fullnameOverride: demo-api
          ingress:
            enabled: true
    - repoURL: https://github.com/murillo-consulting/kube-aegis-forge.git
      targetRevision: gitops
      ref: images
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: latest
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
