"""Write the small, generated image-values contract used by the GitOps branch."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

DIGEST_PATTERN = re.compile(r"^sha256:[0-9a-f]{64}$")
REPOSITORY_PATTERN = re.compile(r"^ghcr\.io/[a-z0-9][a-z0-9._/-]*$")
SAFE_TEXT_PATTERN = re.compile(r"^[A-Za-z0-9._-]{1,64}$")
ENVIRONMENTS = {"local", "aws"}


def validated_digest(value: str) -> str:
    if not DIGEST_PATTERN.fullmatch(value):
        raise argparse.ArgumentTypeError("digest must be sha256 followed by 64 lowercase hexadecimal characters")
    return value


def validated_repository(value: str) -> str:
    if not REPOSITORY_PATTERN.fullmatch(value):
        raise argparse.ArgumentTypeError("repository must be a lowercase ghcr.io path")
    return value


def validated_text(value: str) -> str:
    if not SAFE_TEXT_PATTERN.fullmatch(value):
        raise argparse.ArgumentTypeError("build metadata contains unsupported characters")
    return value


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-digest", type=validated_digest)
    parser.add_argument("--root", type=Path)
    parser.add_argument("--environment", choices=sorted(ENVIRONMENTS))
    parser.add_argument("--repository", type=validated_repository)
    parser.add_argument("--digest", type=validated_digest)
    parser.add_argument("--version", type=validated_text)
    parser.add_argument("--git-sha", type=validated_text)
    args = parser.parse_args()
    if args.check_digest:
        return args
    required = (args.root, args.environment, args.repository, args.digest, args.version)
    if any(value is None for value in required):
        parser.error("promotion mode requires root, environment, repository, digest, and version")
    return args


def main() -> None:
    args = parse_args()
    if args.check_digest:
        print(args.check_digest)
        return

    root = args.root.resolve()
    destination = (root / "platform" / "environments" / args.environment / "image-values.yaml").resolve()
    if root not in destination.parents:
        raise SystemExit("refusing to write outside the requested GitOps worktree")
    destination.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# Generated by a verified promotion workflow. Do not edit manually.\n"
        "image:\n"
        f"  repository: {args.repository}\n"
        '  tag: ""\n'
        f"  digest: {args.digest}\n"
        "  pullPolicy: IfNotPresent\n"
        "build:\n"
        f"  version: {args.version}\n"
        f'  gitSha: "{args.git_sha or ""}"\n'
    )
    destination.write_text(content, encoding="utf-8", newline="\n")
    print(destination)


if __name__ == "__main__":
    main()
